=head1 NAME

ifload

=head1 SYNOPSIS

ifload [OPTIONS] I<INTERFACE>

=head1 OPTIONS

=over

=item B<--help>

Show help message.

=item B<--pps>

Add real-time packets per second.

=item B<--avg>=I<SECS>

Add I<SECS> seconds average.

=back

=head1 ARGUMENTS

=over

=item I<INTERFACE>

Specifies the interface to show.

=back

=head1 DESCRIPTION

B<ifload> shows the used bandwidth and packets per second of the
specified network interface in real time.

=head1 AUTHOR

B<ifload> was written by Oliver Hitz <oliver@net-track.ch>.

=head1 LICENSE

Licensed under The MIT License.

